// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef fl_class_win_h
#define fl_class_win_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include"Fl_Gl_Box.H"
#include <FL/Fl_Slider.H>

class fl_clase_win {
public:
  fl_clase_win();
  Fl_Double_Window *my_win;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
  inline void cb_Icono_i(Fl_Button*, void*);
  static void cb_Icono(Fl_Button*, void*);
  inline void cb_Draw_i(Fl_Button*, void*);
  static void cb_Draw(Fl_Button*, void*);
public:
  Fl_Gl_Box *my_gl;
  Fl_Slider *_slide;
private:
  inline void cb__slide_i(Fl_Slider*, void*);
  static void cb__slide(Fl_Slider*, void*);
public:
  void close();
  void show();
  void icono();
};
#endif
