// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "fl_class_win.h"

int main(void) {
	fl_clase_win * win = new fl_clase_win();
	win->show();
	Fl::run();
	return 0;
}
